---
title: "QC Thresholds 3b"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
always_allow_html: true
output:
  html_fragment:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(results='asis', echo=FALSE, warning=FALSE, message = FALSE)
# needed for trouble shooting
boo_DEBUG <- FALSE
if(boo_DEBUG==TRUE){
  # myConfig <- file.path(system.file(package="ContDataQC"), "extdata", "config.ORIG.R")
  # source(myConfig)
}## IF ~ boo_DEBUG ~ END
```

# Customizing QC flag test thresholds

We strongly encourage people with one or more years of continuous data to evaluate the performance of the QC test thresholds for each parameter at each site and customize the configuration file as needed. 

You should also consider what units you’d like to use. If you are working with lakes and prefer to use meters over feet, click [here](https://github.com/Blocktt/ShinyAppDocuments/tree/main/ContDataQC/Custom_QC_Files) to download a default configuration file that has been converted to meters. 

## Evaluate Thresholds

If you have one or more years of continuous data for a site, we strongly encourage you to evaluate the performance of the QC test thresholds for each parameter at that site and customize the configuration file if needed.

Click here for instructions on how to generate pivot tables and plots to evaluate thresholds for the Unrealistic values ('Gross range') and Spike tests. 
Another option is to use R code written by Tim Martin (Minnesota DNR) to generate statistical outputs that can help inform thresholds for all four QC tests. Click here to download the R scripts and instructions. 

To aid with documentation of the threshold evaluation process, click here to download an Excel worksheet that lists the default thresholds for each parameter and has a column where you can enter the customized values for a given site as well as rationale for making the changes.  When doing this, make sure you consider what units you are using (as well as what the defaults are), since units have a large effect on thresholds. . 

## Edit Thresholds

Click here for instructions on how to edit thresholds and create customized configuration files. There are two options (see below). For either option, save the customized configuration file in a folder that is easy to find so that you can reuse the file each time you QC data for that site. It is helpful to include the StationID and other relevant information in the file name (for example, if thresholds are customized for a particular season). 

After you save the file, go to the 'upload custom thresholds' tab, browse to the custom thresholds file, upload the file and then, under 'Main functions', generate the QC reports. If you forget the upload step, the default QC thresholds will be used.

### Option 1, use the interactive functions shown left and below.

* Select a parameter using the drop-down menu

* Edit thresholds using boxes below

* Save changes (for each parameter)

* Download custom thresholds file

If you do not want to use the default units, you will need to use Option 2.

Acknowledgment: Tim Martin (MN DNR) wrote the R code that we used for the 
interactive functions below.

### Option 2, download the default configuration file, open the file in R or Notepad++, make edits and save.

Configuration files can be downloaded here -

*	Default, with hydrologic parameters in feet

*	Hydrologic parameters in meters
Navigate to the ‘QC tests and calculations’ section. Edit thresholds as desired. Save the file.

When you download the configuration file(s), you will see two types of files: an R file (.R) and a text (.txt) file for users who do not have R installed on their computer. You can download R from this website: https://cran.r-project.org/. You may also want to download RStudio, which is a separate program but is a useful code editor and interface for R. If you cannot install R on your computer, we recommend use Notepad or Notepad + + (some people prefer Notepad ++ because it has color-coding).

## Upload Custom Thresholds

Click the 'Browse' button (to the left) and select the desired customized configuration file. The status bar will tell you when the file has been uploaded. A new button will appear that gives you the option of returning to the default configuration file. Do not click this unless you change your mind and no longer want to use the customized file.

Go to the 'Main Functions' tab; select the desired input file(s); run them through the QC function. Save the output to the desired location. Open the Word or html QC report and scroll to the 'Thresholds, Quick Reference' table (in the middle section of the report). Verify that the correct thresholds were used.

Be aware that each time you close and reopen the Shiny app, it will automatically revert back to the default configuration file. Also – remember the sequencing! If you forget to upload the customized configuration file prior to running the QC function, it will use the default thresholds.
