---
title: "Main Functions 5a"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
always_allow_html: true
output:
  html_fragment:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(results='asis', echo=FALSE, warning=FALSE, message = FALSE)
# needed for trouble shooting
boo_DEBUG <- FALSE
if(boo_DEBUG==TRUE){
  # myConfig <- file.path(system.file(package="ContDataQC"), "extdata", "config.ORIG.R")
  # source(myConfig)
}## IF ~ boo_DEBUG ~ END
```

### QC reports

**Example** [QC reports](Example_QCreports.zip) [ZIP] 

Instructions for generating QC reports using the ContDataQC Shiny app:

1.	Click the ‘Browse’ button and select the input file(s) from the Data1_RAW 
folder. You can run multiple files at once. The status bar will tell you when 
the upload is complete.

2.	Select ‘QC raw data’ from the ‘Choose operation to perform’ drop-down menu

3.	Click the ‘Run operation’ button will appears. A status bar will
appear in the lower right corner.

4.	After the function is done running, click the ‘Download’ button that appears. Click this button.

5.	You will be prompted to save a zipped file named ‘QCRaw.date_time.’ Save it in the Data2_QC folder.

6.	Unzip/extract the file(s). After file is unzipped, a new folder called ‘data’ will appear, which contains QC reports that have ‘QC_’ as the prefix in the file name. The original zipped file can be deleted if desired.

7.	Open the QC reports. There are two types of outputs: a Word document Data Quality Control Report  and a comma-delimited (.csv) spreadsheet. If users prefer a Hypertext Markup Language (HTML) report instead of Word, they can change the format in the configuration file (this requires some familiarity with R code). The reports include results from the ‘flag’ tests (gross, spike, rate of change and flat line), missing data checks, and time series plots.

8.	Review each set of files, check flagged data points, do visual checks on the time series plots, and decide if and how to make corrections. For tips on the QC process, see the **About >> Tips** subtab. 

The Data Quality Control Report is organized into four main sections (starting with an overall summary followed by summaries for each parameter):

1.	Data file information (siteID, date range, parameters, recording interval, QC test thresholds reference table).

2.	‘Count’ tables (# measurements/day) so that you can find inconsistencies 
(too few measurements, indicating missing data, or too many measurements) for each parameter.

3.	Results from the four ‘flag’ tests (gross, spike, rate of change and flat line), which show the # of entries for each parameter marked as pass (P), suspect (S), fail (F), missing data (X) or not available (NA).

4.	Time series plots for each individual parameter and two sets of combined 
parameters (water and air temperature; water temperature and water level). If the input file includes discrete/in situ values that were taken during site visits for accuracy checks, the discrete values are plotted with the sensor data.

The CSV file contains the time series data from the sensor plus additional data columns with flags for each test and parameter (e.g., Flag.Spike.Water.Temp.C, Flag.Flat.Water.Temp.C), comment fields for each parameter (e.g., Comment.MOD.Water.Temp.C) so that the user can document rationale for any changes, and a duplicate set of the original ‘raw’ data values (e.g., RAW.Water.Temp.C). The ‘raw’ values are included  so that the user can maintain documentation of changes that are made and if needed go back to change how they handled a correction.

Currently there are no automated corrections programmed into the QC function. 
The user must make the changes manually. For tips on the QC process, see the 
‘About - Tips’ subtab. 
