---
title: "QC Thresholds 4d"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
always_allow_html: true
output:
  html_fragment:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(results='asis', echo=FALSE, warning=FALSE, message = FALSE)
# needed for trouble shooting
boo_DEBUG <- FALSE
if(boo_DEBUG==TRUE){
  # myConfig <- file.path(system.file(package="ContDataQC"), "extdata", "config.ORIG.R")
  # source(myConfig)
}## IF ~ boo_DEBUG ~ END
```

## Upload Custom Thresholds

Click the 'Browse' button (to the left) and select the desired customized 
configuration file. The status bar will tell you when the file has been 
uploaded. A new button will appear that gives you the option of returning to the
default configuration file. Do not click this unless you change your mind and no longer want to use the customized file.

Go to the ‘Run Functions’ tab; verify that the correct configuration file has been uploaded (by checking the file name); select the desired input file(s); run them through the QC function. Save the output to the desired location. Open the Word QC report and scroll to the ‘Thresholds, Quick Reference’ table (in the middle section of the report). Verify that the correct thresholds were used.

Be aware that each time you close and reopen the Shiny app, it will 
automatically revert back to the default configuration file. Also – remember the
sequencing! If you forget to upload the customized configuration file prior to 
running the QC function, it will use the default thresholds.

Click [here](Custom_QC_Config_ECO66G20_test1.R) [R] to download an example of a modified configuration file that you can try uploading to the Shiny app.
