---
title: "Test Date"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
always_allow_html: true
output:
  html_fragment:
    toc: yes
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(results='asis', echo=FALSE, warning=FALSE, message = FALSE)
# needed for trouble shooting
boo_DEBUG <- FALSE
if(boo_DEBUG==TRUE){
  # myConfig <- file.path(system.file(package="ContDataQC"), "extdata", "config.ORIG.R")
  # source(myConfig)
}## IF ~ boo_DEBUG ~ END
```

Below are test files that you can download and run through the Shiny app. They are from Onset HOBO U20 water level loggers (non-vented pressure transducers) and miniDOT DO sensors. Please contact us if you have example files from other sensors that you would like us to add to this website.

# Test files
* [Onset HOBO U20](TestData_HOBOU20_20220822.zip) [ZIP]
* [miniDOT DO](TestData_miniDOT.zip) [ZIP]

## Onset HOBO
The Onset HOBO U20 test data consist of two comma-separated values (CSV) files. The files are from the same site but cover two different time periods. You'll see two folders:

* **Test**

  + The two HOBO U20 test files are in the Data0_Original folder. Go to the **Automated Reformat – Onset HOBO** tab and run both files through the reformatting function. Multiple files can be run through the function at the same time (in ‘batches’). The function reformats the files so that they are ready to run through the QC report function. Next, go to the **Main Functions-Import Files** tab, import the reformatted files, run them through the ‘QC raw data’ function (multiple files can be run through the function at the same time), check the flagged data (edit if needed),  aggregate the two QC’d CSV files with the ‘Aggregate QC’ed data’ function, and run the ‘Summary Statistics’ function to summarize the data. 
  
* **Completed**

    + This folder has the complete set of outputs for both files so that you can see examples of the QC reports and other outputs without having to run the test data through the functions yourself. 

## miniDOT DO Sensors

The miniDOT DO test files are from one site and one deployment period.
You’ll see two sets of folders. Within each folder are example input and output files.

* **miniDOT_concatenate** - When data are initially downloaded from miniDOT sensors, there are separate .txt files for each day (in this example, 325 individual files). Go to the **Automated Reformat – miniDOT** tab and run the **Concatenate** function to combine them all into one file. 

*	**miniDOT_reformat** – run the combined file through the Reformat function. The function reformats the file so that it is ready to run through the QC report function. Next, go to the Main **Functions-Import Files** tab, import the reformatted file, run it through the ‘QC raw data’ function, and check the flagged data (edit if needed).
