---
title: "Main Functions 5a"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
always_allow_html: true
output:
  html_fragment:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(results='asis', echo=FALSE, warning=FALSE, message = FALSE)
# needed for trouble shooting
boo_DEBUG <- FALSE
if(boo_DEBUG==TRUE){
  # myConfig <- file.path(system.file(package="ContDataQC"), "extdata", "config.ORIG.R")
  # source(myConfig)
}## IF ~ boo_DEBUG ~ END
```

### Aggregate Output

**Example file** [Aggregate output](Example_Aggregate.zip) [ZIP]

Instructions for generating aggregated reports using the ContDataQC Shiny app:

1.	Click the ‘Browse’ button and select the QC’d input files that you’d like to combine. The input files need to be from the same site and share common parameters. The status bar will tell you when the upload is complete.

2.	Select ‘Aggregate QC’d data’ from the ‘Choose operation to perform’ drop-down menu.

3.	Click the ‘Run operation’ button that appears. A status bar will appear in the lower right corner.

4.	After the function is done running, click the ‘Download’ button that appears. You will be prompted to save a zipped file named ‘Aggregate.date_time.’ Save it in the Data3_Aggregated folder.

5.	 Unzip/extract the file(s). After file is unzipped, a new folder called ‘data’ will appear. If a ‘data’ folder already exists, outputs will go into that folder. The aggregate reports have ‘DATA_’ as the prefix in the file name. The original zipped file can be deleted if desired.

6.	Open and review the aggregated reports. As with the QC output, there are two types of outputs: a Word document Data Quality Control Report and a comma-delimited (.csv) spreadsheet. If users prefer a Hypertext Markup Language (HTML) report instead of Word, they can change the format in the configuration file (this requires some familiarity with R code).
