---
title: "Advanced"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
always_allow_html: true
output:
  html_fragment:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(results='asis', echo=FALSE, warning=FALSE, message = FALSE)
# needed for trouble shooting
boo_DEBUG <- FALSE
if(boo_DEBUG==TRUE){
  # myConfig <- file.path(system.file(package="ContDataQC"), "extdata", "config.ORIG.R")
  # source(myConfig)
}## IF ~ boo_DEBUG ~ END
```
# Advanced

Some users may prefer to use the 
<a href="https://github.com/leppott/ContDataQC" data-once="external-links protected-links" target="_blank">R code<svg class="icon icon--exit is-spaced-before" role="img"> == $0 <title>Exit EPA's website</title><use href="https://www.epa.gov/themes/epa_theme/images/sprite.svg#launch"></use></svg></a> 
instead of the Shiny app. The example code in Figure 1 shows how to run the main
functions when using the default settings in the R package. After the user 
directs R to the correct directories and selects the operation (QCRaw, Aggregate
or SummaryStats), there are several places in the code where the user needs to 
make entries (e.g., SiteID, sensor type, and start/end date). R will read 
through the file names in the directory, select files that match the criteria 
and generate outputs for each input file that matches the criteria. 

Users with intermediate to advanced-level R skills can customize the settings 
(e.g., add new parameters, change units, change file naming and formatting 
requirements, change the format of one of the QC reports from Word to html or 
PDF) by editing a plain text [configuration file](Config_default.zip) [ZIP].  Users 
have more flexibility using the Shiny app versus R package when it comes to 
setting directories and file naming schemes because they can browse to the 
desired input file(s).
