---
title: "Main Functions 5a"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
always_allow_html: true
output:
  html_fragment:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(results='asis', echo=FALSE, warning=FALSE, message = FALSE)
# needed for trouble shooting
boo_DEBUG <- FALSE
if(boo_DEBUG==TRUE){
  # myConfig <- file.path(system.file(package="ContDataQC"), "extdata", "config.ORIG.R")
  # source(myConfig)
}## IF ~ boo_DEBUG ~ END
```

### Summary Statistics

**Example file** [Summary Stats output](Example_SumStats.zip) [ZIP]

Instructions for generating summary statistics reports using the ContDataQC Shiny app:

1.  Click the 'Browse' button and select the desired input file from the 
Data3_Aggregated folder. The status bar will tell you when the upload is 
complete.

2.  Select 'Summary statistics' from the 'Choose operation to perform' drop-down menu.

3.  Click the 'Run operation' button that appears. A status bar will appear in the lower right corner.

4.  After the function is done running, click the ‘Download’ button that appears. You will be prompted to save a zipped file named ‘SummaryStats.date_time.’ Save it in the Data4_Stats folder.

5.  Unzip/extract the file(s). After file is unzipped, a new folder called ‘data’ will appear. If a ‘data’ folder already exists, outputs will go into that folder. The summary stats reports have ‘STATS_’ as the prefix in the file name. The original zipped file can be deleted if desired.

6.  Open and review the summary statistics reports. There should be two sets of CSV files and a PDF with time series plots for each parameter. One of the CSVs has daily mean values; the other has a wider range of summary statistics (e.g., min, median, max, quartiles).
