---
title: "Test Date"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
always_allow_html: true
output:
  html_fragment:
    toc: yes
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(results='asis', echo=FALSE, warning=FALSE, message = FALSE)
# needed for trouble shooting
boo_DEBUG <- FALSE
if(boo_DEBUG==TRUE){
  # myConfig <- file.path(system.file(package="ContDataQC"), "extdata", "config.ORIG.R")
  # source(myConfig)
}## IF ~ boo_DEBUG ~ END
```

# Test Data

Test data can be downloaded [here](https://github.com/Blocktt/ShinyAppDocuments/tree/main/ContDataQC/TestData_Files). 
The test data consist of two
comma-separated values (CSV) files that came from Onset U20 water level
loggers (non-vented pressure transducers) that were deployed in the air
and water. The files are from the same site but cover two different time
periods.


You'll see two sets of folders:

-   **Test**

    -   The two files are in the Data0_Original folder and are ready to
        be run through the HOBOware Reformat function. Next, run them
        through the Main Functions to generate QC reports, aggregate the
        two QC'd CSV files and summarize the data.

-   **Completed**

    -   This folder has the complete set of outputs for both files. .so
        that you can see examples of the QC reports and other outputs
        without having to run the test data through the R tool yourself.
        We are happy to add more test data to this website. If you have
        example files that you would like to contribute, please send
        them to Jen Stamp
        ([Jen.Stamp\@tetratech.com](mailto:Jen.Stamp@tetratech.com){.email}).
