---
title: "Report, Deployment Comparison"
subtitle: "ContDataQC"
author: "`r Sys.getenv('USERNAME')`"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: no
  word_document:
    toc: yes
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(results='asis', echo=FALSE, warning=FALSE)
# needed for trouble shooting
boo_DEBUG <- TRUE
if(boo_DEBUG==TRUE){
  myConfig <- file.path(system.file(package="ContDataQC"), "extdata"
                        , "config.ORIG.R")
  source(myConfig)
  
  
  
  
  
  
}
```

# DATA FILE INFORMATION

Similar to other reports.
Have to add in code.

```{r data_file_info}
 #  # Report Info
 #  myReportDate <- format(Sys.Date(), ContData.env$myFormat.Date)
 #  cat(paste("**Report Date:** ", myReportDate, "\n\n", sep=""))
 #  myUser <- Sys.getenv("USERNAME")
 #  cat(paste("**Generated By:** ", myUser, "\n\n", sep=""))
 #  
 #  #filename
 #  cat("**Filename:** ", strFile, "\n\n",sep="")
 # 
 #  mySiteID <- data.import[1,ContData.env$myName.SiteID]
 #  
 #  cat(paste("**SiteID:** ",mySiteID,"\n\n",sep=""))
 #  
 #  if(exists("fun.myData.DateRange.Start")==TRUE){
 #    POR.Requested <- paste(fun.myData.DateRange.Start
 #                           ," to "
 #                           ,fun.myData.DateRange.End
 #                           , sep="")
 #  } else {
 #    POR.Requested <- "NA"
 #  }
 #  cat(paste("**Period of Record, Requested:** "
 #            ,POR.Requested,sep=""
 #            ,collapse="\n\n"))
 #  
 #  myNumRecords <- nrow(data.import) 
 #  # 20170228, mod from records 10 and 11 to half way point
 #  
 #  # myTimeDiff <- difftime(data.import[10,ContData.env$myName.DateTime]
 #  #,data.import[11,ContData.env$myName.DateTime],units="mins")
 #  #x <- data.import[,ContData.env$myName.DateTime]
 #  myT <- strptime(data.import[,ContData.env$myName.DateTime]
 #                  ,format=ContData.env$myFormat.DateTime)
 #  myTimeDiff.all <- difftime(myT[-1],myT[-length(myT)],units="mins")
 #  myTimeDiff <- median(as.vector(myTimeDiff.all),na.rm=TRUE)
 # 
 #  cat(paste("\n\n**Period of Record, Actual:**"
 #            ,min(data.import[,ContData.env$myName.Date])
 #            ," to "
 #            ,max(data.import[,ContData.env$myName.Date])
 #            ,"\n\n"
 #            ,sep=""))
 #       
 #  cat(paste("**Recording Interval:** ",myTimeDiff[1]," minutes\n\n",sep=""))
 #  
 #  if(exists("strFile.DataType")==TRUE){
 #    myDataType <- strFile.DataType
 #  } else {
 #    myDataType <- "NA"
 #  }
 #  cat(paste("**Data Type:** ",myDataType,"\n\n",sep=""))  # need to do better
 #  
 #   myParameters.ALL     <- ContData.env$myNames.DataFields[ContData.env$myNames.DataFields 
 #                                                           %in% names(data.import)==TRUE] 
 #   myParameters.Lab.ALL <- ContData.env$myNames.DataFields.Lab[ContData.env$myNames.DataFields 
 #                                                               %in% names(data.import)==TRUE]
 #   # Filter out Discrete
 #   myParameters     <- myParameters.ALL[!grepl(ContData.env$myPrefix.Discrete,myParameters.ALL)]
 #   myParameters.Lab <- myParameters.Lab.ALL[
 #                                           !grepl(ContData.env$myPrefix.Discrete
 #                                                   ,myParameters.Lab.ALL)]
 #   
 #   
 # #cat("**Parameters:** ",paste(myParameters.Lab,", ",sep=""),"\n\n",sep="")
 #  # above line not working, preventing pandoc conversion to WORD
 #  #cat("**Included Parameters:** \n\n")
 #  cat("**Parameters Included:** ",paste(myParameters.ALL
 #                                        ,", "
 #                                        ,sep="")
 #      ,"\n\n"
 #      ,sep="")
```

# DEPLOYMENT COMPARISON, BY PARAMETER
```{r CompDeploy, eval=TRUE, echo=FALSE}
# library(ggplot2)
#myDir <- tempdir()
myDir <- "C:\\Users\\Erik.Leppo\\OneDrive - Tetra Tech, Inc\\MyDocs_OneDrive\\_HOME\\RMN\\Function_DeploymentCompare"
# source config.R

fun.col.Param <- "Water.Temp.C"
fun.CompHours <- 25
fun.CompHoursMax <- 12
fun.logdeploy.start <- "start"
fun.logdeploy.end = "end"
fun.col.DateTime = "Date.Time"
fun.col.logdeploy <- "Logger.Deployment"

# may just run an RMD as a Log file.  Nothing else is saved.

logdeploy.terms <- c(fun.logdeploy.start, fun.logdeploy.end)

col2keep <- c(fun.col.DateTime, fun.col.Param, fun.col.logdeploy)

df <- read.csv(file.path(myDir
                         , "Data3_Aggregated"
                         , "DATA_test2_Aw_20130101_20141231.csv"))

df[, fun.col.DateTime] <- as.POSIXct(df[, fun.col.DateTime]
                                     , format = ContData.env$myFormat.DateTime 
                                     , tz = ContData.env$myTZ)


df_small <- df[df[, fun.col.logdeploy] %in% c(logdeploy.terms), col2keep]

n_start <- sum(df[, fun.col.logdeploy] == fun.logdeploy.start, na.rm = TRUE)
n_end   <- sum(df[, fun.col.logdeploy] == fun.logdeploy.end, na.rm = TRUE)
n_deploy <- min(n_start, n_end)
msg <- paste0("**Number of deployments identified:** ", n_deploy, "\n\n")
cat(msg)

date_start <- df_small[df_small[, fun.col.logdeploy] == fun.logdeploy.start, fun.col.DateTime]
date_end <- df_small[df_small[, fun.col.logdeploy] == fun.logdeploy.end, fun.col.DateTime]

# Create deployment comps
# Loop through n_deploy
# will have one less comparison then the number of deployments

for(i in seq_len(n_deploy)) {
  
  msg <- paste0("## Deployment: ", i, "\n\n")
  cat(msg)
  
  # if last one skip
  if(i == n_deploy) {
    msg <- paste0("Last deployment in file, "
                  , i
                  , "/"
                  , n_deploy
                  , " .  \n"
                  , "No comparison able to be made to 'next' deployment."
                  , "\n\n")
    cat(msg)
    next
  }## IF ~ i == ndeploy
  
  
  # Start and End Dates
  i_A_end <- date_end[i]
  i_B_start <- date_start[i + 1]
  # 3600 seconds = 1 hour
  i_A_start <- i_A_end - (fun.CompHours * 3600)
  i_B_end   <- i_B_start + (fun.CompHours * 3600)
  # Compare time
  i_diff <- as.vector(difftime(i_B_start, i_A_end, units = "hours"))
  
  
  # Times
  msg <- paste0("**A, Start:** ", i_A_start,"\n\n")
  cat(msg)
  msg <- paste0("**A, End:   ** ", i_A_end,"\n\n")
  cat(msg)
  msg <- paste0("**B, Start:** ", i_B_start,"\n\n")
  cat(msg)
  msg <- paste0("**B, End:   ** ", i_B_end,"\n\n")
  cat(msg)
  msg <- paste0("**Time difference between deployments (hours):** "
                , i_diff
                , "\n\n")
  cat(msg)
  msg <- paste0("**Maximum allowable difference (hours):** "
                , fun.CompHoursMax
                , "\n\n")
  cat(msg)
  
  
  # QC, stop if gap too large
  if(i_diff > fun.CompHoursMax) {
    msg <- paste0("Maximum time difference exceeded.  "
                  , "Skipping deployment."
                  , "\n\n")
    cat(msg)
    next
  }## IF ~ i_diff ~ END
  
  col_Comp <- "Comp"

  # Identify the range to examine
  df$Comp <- "X"
  mark_A <- df$Date.Time > i_A_start & df$Date.Time <= i_A_end
  mark_B <- df$Date.Time >= i_B_start & df$Date.Time < i_B_end
  df[mark_A, col_Comp] <- "A"
  df[mark_B, col_Comp] <- "B"

  # Loop through parameters
  
  # get data for comparison
  vec_A <- df[df[, col_Comp] == "A", fun.col.Param]
  vec_B <- df[df[, col_Comp] == "B", fun.col.Param]
  A_last <- vec_A[length(vec_A)]
  B_first <- vec_B[1]
  diff_spike <- abs(B_first - A_last)

  # Comment out t test
  # Run function
  #rquery.t.test(vec_A, vec_B, paired = TRUE)
  # wilcoxon test
  #wilcox.test(vec_A, vec_B, paired = TRUE)
  
  col4plot <- c("SiteID", "Date.Time", fun.col.Param, col_Comp)
  
  df_plot <- df[df[, col_Comp] %in% c("A", "B"), col4plot]

  # Spike test
  msg <- paste0("**A, Last measured value:** "
                , A_last
                ,"\n\n")
  cat(msg)
  msg <- paste0("**B, First measured value:** "
                , B_first
                , "\n\n")
  cat(msg)
  msg <- paste0("**Spike test threshold:** "
                , 1.5
                , "\n\n") 
  cat(msg)
  msg <- paste0("**Measured value difference:** "
                , diff_spike
                , "\n\n")
  cat(msg)
  msg <- "Some statement about spike test, Pass or Fail\n\n"
  cat(msg)  
  # Get parameter
  
  
  
  lab.title <- paste0("Deployment end/start comparison; ", i_A_end)
  lab.subtitle <- paste0(i, " (A) and ", i+1, " (B)")

  # Plot, box
  p_box <- ggplot2::ggplot(df_plot, ggplot2::aes_string(x = col_Comp
                                                        , y = fun.col.Param
                                                        , fill = col_Comp)) + 
    ggplot2::geom_boxplot() + 
    ggplot2::labs(title = lab.title
        , subtitle = lab.subtitle
        , x = "Deployments") + 
    ggplot2::theme_bw() +
    ggplot2::theme(legend.position = "none") 
  print(p_box)
  cat("\n\n")
  
  # Plot, time series
  #x_vline <- length(vec_A) + .5 # (i_A_end + i_B_start)/2
  x_vline <- i_A_end + i_diff/2 * 3600
  
  # scale_x_date(labels = date_format("%m-%Y"))
  # ensure data is date 
  #df_plot[, "Date.Time"] <- as.Date.POSIXct(df_plot[, "Date.Time"])
  
  p_scat <- ggplot2::ggplot(df_plot, ggplot2::aes_string(x = fun.col.DateTime
                                                        , y = fun.col.Param
                                                        , color = col_Comp)) +
      ggplot2::geom_point() + 
      ggplot2::geom_vline(xintercept = x_vline) + 
      ggplot2::labs(title = lab.title, subtitle = lab.subtitle) +
      ggplot2::theme_minimal() +
      ggplot2::theme(legend.title = ggplot2::element_blank())
  print(p_scat)
  cat("\n\n")


}## FOR ~ i ~ END
```
